packages:
  - apps/*
  - packages/*

settings:
  ignoreBuildScripts: false
  onlyBuiltDependencies:
    - esbuild
    - sharp
    - unrs-resolver
allowBuilds:
  esbuild: true
  sharp: set this to true or false
  unrs-resolver: set this to true or false
